import mongoose from "mongoose";
import Project from "../src/models/Project.js";

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) throw new Error("MONGODB_URI is not set");

const nw = (name) => ({ name, why: "" });

const updates = {
  "nepal-denim": {
    title: "Nepal Denims",
    oneLiner:
      "A production e-commerce and operations platform I designed and built for Nepal Denims, a Kathmandu-based children's fashion business. The project combines a customer-facing storefront, a full administrative back office, content management, order processing, inventory operations, security controls, monitoring, and production infrastructure in one Next.js application.",
    status: "Live in production",
    duration: "August 2026 – Present",
    role: "Solo Full-Stack Developer / Freelance Developer",
    teamSize: "1 developer, working directly from client requirements",
    links: { demo: "https://nepaldenims.com", github: "", docs: "" },
    overview: {
      purpose: "I built Nepal Denims to give the business a complete digital commerce platform instead of relying primarily on manual or social-media-driven selling processes.",
      targetUsers: "Retail customers browsing and purchasing children's clothing; wholesale and bulk-order buyers; internal staff managing products, orders, inventory, content, customers, returns, promotions, and operations.",
      businessProblem: "",
      objectives: [
        "Production storefront with category browsing, product variants, cart, wishlist, search, product comparison, quick view, checkout, and account flows",
        "Bulk-order and inquiry workflows designed for Nepal Denims' wholesale-oriented business model",
        "Administrative platform for commerce, inventory, CMS, customers, marketing, permissions, monitoring, and operational workflows",
        "Nepal-specific payment and delivery support",
        "Centralized inventory architecture covering reservations, physical stock movement, production, transfers, adjustments, and returns",
        "Production-grade SEO, security, observability, validation, and deployment practices",
      ],
    },
    techStack: {
      frontend: ["Next.js 16 — App Router and Server Components", "React 19", "TypeScript", "Design-token-driven CSS architecture", "Zustand for client-side state", "BroadcastChannel for cross-tab state synchronization", "shadcn / Base UI primitives for administrative interfaces", "React Markdown + remark-gfm for CMS content rendering"].map(nw),
      backend: ["Next.js Server Actions", "Next.js Route Handlers", "Zod validation at server boundaries", "Centralized domain services for inventory, orders, returns, authentication, monitoring, email, storage, and support"].map(nw),
      database: ["PostgreSQL on Neon", "Prisma ORM 7", "Separate production and development database branches", "Transactional writes for stock-sensitive and money-sensitive operations"].map(nw),
      auth: ["Auth.js v5", "Credentials authentication with bcrypt", "Google OAuth", "JWT-based sessions", "ADMIN, STAFF, and CUSTOMER role model", "StaffPermission-based module authorization with secure-by-default access"].map(nw),
      ai: [],
      devops: ["Vercel", "GitHub Actions", "Vercel Blob", "Vercel Web Analytics", "Vercel Speed Insights", "Sentry", "UptimeRobot", "Resend + React Email"].map(nw),
      deployment: [],
      libraries: [],
    },
    features: [
      { name: "Storefront Catalog & Product Discovery", description: "I built a server-rendered storefront with category browsing, product detail pages, size and color variants, product imagery, quick view, wishlist, cart, comparison and bulk-order actions.", implementation: "Product and category content is rendered server-side for crawlability and fast first response. Interactive controls remain isolated client components. Product variants remain synchronized with price, stock, size, and color availability.", challenges: "", benefits: "Customers can discover products quickly while Nepal Denims retains structured catalog control through the admin panel." },
      { name: "Checkout & Payments", description: "Checkout is designed around server-authoritative pricing and inventory correctness.", implementation: "Server recomputes order totals from current product and variant data. Client-submitted prices are never treated as authoritative. Order creation and stock operations are coordinated transactionally. Cash on Delivery is supported for the local market. eSewa and Khalti payment flows are integrated into the payment architecture. Payment status and order status are modeled independently for operational clarity.", challenges: "", benefits: "The checkout process protects against stale pricing, invalid totals, and stock inconsistencies while supporting payment methods relevant to Nepal." },
      { name: "Bulk Ordering", description: "Nepal Denims serves wholesale and larger-volume buyers, so bulk ordering is treated as a dedicated workflow rather than a normal cart with larger quantities.", implementation: "BulkInquiry and BulkInquiryItem model the pre-order commercial discussion. Inquiry creation does not incorrectly consume inventory. Confirmed conversion into an Order enters the same order and inventory domain as normal commerce.", challenges: "", benefits: "Wholesale customers can engage with the business without forcing retail checkout assumptions onto large orders." },
      { name: "Admin Panel", description: "I built a full back-office environment under /admin for daily store operations: Dashboard, Orders, Bulk Orders, Products, Categories, Brands, Inventory, Customers, Reviews, Promotions, Coupons, Flash Sales, Campaigns, Email Campaigns, Push Notifications, CMS content, Team Members, Roles & Permissions, Activity Logs, Settings, System Health.", implementation: "Every privileged mutation is validated server-side and protected independently from the UI.", challenges: "", benefits: "Non-technical staff can operate the business from one system instead of depending on the developer for routine updates." },
      { name: "Inventory Management", description: "I designed the inventory system as a centralized domain rather than allowing individual pages or order flows to mutate stock independently. Core concepts: InventoryBalance, InventoryReservation, StockMovement, Location, ProductionBatch, StockTransfer, StockAdjustment, StockCount.", implementation: "Core operations: Reserve, Release, Consume, Receive production, Transfer stock, Adjust stock, Reconcile counts, Return/restock. Web, manual, and converted bulk orders use the same inventory domain. Order creation reserves inventory; cancellation releases reservations. Concurrency-sensitive writes are handled transactionally.", challenges: "", benefits: "Inventory behavior is consistent regardless of where an order originates, reducing overselling, duplicated stock logic, and reconciliation problems." },
      { name: "Production, Transfers & Adjustments", description: "The inventory module supports more than storefront stock: production batch tracking, stock transfers between warehouses/factories/outlets/online locations, and controlled stock adjustments/count reconciliation.", implementation: "Preserves batch-level and movement-level operational history for auditability.", challenges: "", benefits: "" },
      { name: "Returns & Support", description: "I implemented structured return and support workflows instead of treating returns as arbitrary stock edits. Return lifecycle: Requested → Approved → Received → Restocked / Refunded.", implementation: "Return handling is connected to order state and inventory behavior. SupportTicket and TicketMessage provide a structured customer-support trail.", challenges: "", benefits: "" },
      { name: "Cross-Tab Cart Synchronization", description: "Cart changes remain synchronized across multiple open browser tabs.", implementation: "Zustand maintains the active client state; BroadcastChannel distributes the authoritative post-mutation cart state; receiving tabs hydrate directly from the updated payload, avoiding unnecessary duplicate server round trips.", challenges: "", benefits: "I eliminated stale-cart behavior while keeping synchronization lightweight." },
      { name: "Authentication & Staff Permissions", description: "The application supports customer accounts and administrative access with clear authorization boundaries.", implementation: "Credentials + OAuth authentication, JWT sessions, bcrypt password hashing. ADMIN has full administrative capability; STAFF receives explicitly granted module permissions; missing StaffPermission rows mean access is denied. Protected actions revalidate the authenticated session server-side.", challenges: "", benefits: "" },
      { name: "System Health", description: "I created an internal operational dashboard that brings multiple infrastructure signals into one admin view: PostgreSQL reachability/latency, Sentry issue visibility, UptimeRobot endpoint status, Vercel analytics, storefront/admin/checkout/auth endpoint visibility.", implementation: "External monitoring integrations fail safely so a third-party monitoring outage does not break the admin system itself.", challenges: "", benefits: "" },
      { name: "Transactional Email", description: "Resend + React Email power transactional communication: order confirmations, order status updates, password resets, stock alerts, team invitations, bulk inquiry notifications.", implementation: "", challenges: "", benefits: "" },
      { name: "SEO Infrastructure", description: "SEO is part of the application architecture rather than an afterthought.", implementation: "generateMetadata, Open Graph metadata, Twitter cards, Product/BreadcrumbList/Organization JSON-LD, dynamic sitemap, robots configuration, human-readable product slugs, noindex rules for private/account/checkout surfaces, server-rendered indexable content.", challenges: "", benefits: "" },
    ],
    architecture: {
      flow: ["Browser", "Next.js App Router", "Server Components / Server Actions", "Domain services", "Prisma", "Neon PostgreSQL", "Resend / Blob / Monitoring services"],
      folderStructure: "src/app/(storefront) · src/app/(auth) · src/app/(admin)/admin · src/app/api · src/components/ui · src/components/admin · src/components/product · src/components/cart · src/components/wishlist · src/lib/auth · src/lib/inventory · src/lib/returns · src/lib/monitoring · src/lib/seo · src/lib/email · src/lib/validation · src/lib/store — the application intentionally keeps UI, domain behavior, persistence, and infrastructure concerns separated.",
      appFlow: "Commerce lifecycle: Customer selection → server-side validation → server-side price calculation → inventory reservation → order creation → payment/order status lifecycle → fulfillment → inventory consumption → transactional communication.",
      authFlow: "Admin lifecycle: Admin request → authenticated server-side session validation → permission validation → domain mutation → database transaction → audit/activity record → UI refresh / notification.",
      requestLifecycle: "",
    },
    databaseDesign: {
      collections: [
        { name: "Commerce", notes: "Product, ProductVariant, ProductImage, Order, OrderItem, Payment, Cart, CartItem, Wishlist, WishlistItem, BulkInquiry, BulkInquiryItem" },
        { name: "Inventory", notes: "InventoryBalance, InventoryReservation, StockMovement, Location, ProductionBatch, StockTransfer, StockAdjustment, StockCount" },
        { name: "Customer Operations", notes: "Return, ReturnItem, SupportTicket, TicketMessage" },
        { name: "Administration & Security", notes: "StaffPermission, AuditLog, RateLimitBucket" },
        { name: "CMS & Merchandising", notes: "CmsPage, HeroSlide, SiteSettings, Category, CategoryShowcaseItem, Brand, SizeChart, SizeChartRow, SizeOption, ColorOption" },
      ],
      reasoning: "Money uses Decimal rather than floating-point values, and order shipping information is snapshotted so historical orders are not changed when a customer later edits an address.",
    },
    apiDocsNote: "The project primarily uses Server Actions for first-party application mutations and Route Handlers where HTTP interfaces are appropriate. Key server interfaces cover authentication, account operations, checkout, orders, bulk inquiries, inventory, returns, support, admin mutations, health checks, monitoring, and CMS operations. External input is validated at server boundaries; business rules live in reusable domain logic instead of being duplicated in UI components.",
    apiDocs: [],
    authFlow: {
      login: "Customer/admin login: credentials or OAuth → Auth.js validation → JWT session → httpOnly cookie → server-side authorization.",
      jwt: "",
      middleware: "Administrative request: request → requireAdminSession() → role/StaffPermission validation → action execution.",
      notes: "Security decisions are always enforced on the server; hiding a button in the UI is never treated as authorization.",
    },
    challenges: [
      { problem: "Multi-Tab Cart Consistency — multiple tabs could hold independent local cart snapshots.", why: "", solution: "I introduced BroadcastChannel synchronization using the authoritative cart payload returned after a successful server mutation.", tradeoffs: "", lessons: "Cart state updates across tabs without an unnecessary second server fetch." },
      { problem: "Authorization Hardening — fine-grained mutations require both authentication and ownership/authorization validation.", why: "", solution: "I audited privileged actions systematically and strengthened identity scoping on sensitive operations.", tradeoffs: "", lessons: "Authorization is enforced at the mutation boundary instead of relying on navigation or UI state." },
      { problem: "Inventory Concurrency — multiple simultaneous orders must not oversell limited inventory.", why: "", solution: "I centralized inventory mutations, defined explicit inventory invariants, and implemented transaction-safe reservation and movement behavior.", tradeoffs: "", lessons: "Retail, manual, bulk, production, transfer, return, and adjustment flows follow one stock model." },
      { problem: "Operational Monitoring — infrastructure status was distributed across multiple vendor dashboards.", why: "", solution: "I consolidated database, error, uptime, and analytics signals into the System Health admin surface.", tradeoffs: "", lessons: "Operational issues can be checked from one internal interface." },
    ],
    performance: { lighthouse: "", techniques: ["Server Components by default", "Client JavaScript restricted to interactive leaves", "next/image responsive delivery", "Vercel Blob-backed media", "Reduced font payload", "Tuned image quality", "Indexed high-frequency database query columns", "Server-side rendering for crawlable content", "Vercel Speed Insights for production visibility"] },
    security: { considerations: ["Server-authoritative order totals", "Transactional inventory and order writes", "bcrypt password hashing", "JWT sessions in httpOnly cookies", "Server-side admin authorization", "Zod validation", "Database-backed login rate limiting", "Decimal money fields", "Security headers", "Secure handling of payment redirects", "Sentry monitoring", "Dependency auditing", "Environment-separated development and production databases"] },
    deployment: { hosting: "Vercel", cicd: "GitHub Actions — validates dependency installation, linting, generated Next.js types, TypeScript correctness, tests, and commit/PR conventions. Vercel preview deployments provide an additional production-style build gate.", prodSetup: "Database: Neon PostgreSQL · Storage: Vercel Blob · Email: Resend · Monitoring: Sentry + UptimeRobot + Vercel Analytics" },
    futureImprovements: ["Richer wholesale workflows", "Deeper inventory analytics", "Location-scoped operational permissions", "Additional payment automation", "Expanded merchandising and campaign tooling", "Continued performance/security hardening"],
    lessonsLearned: ["Domain rules become easier to test and maintain when stock behavior is centralized instead of scattered across order screens.", "Server-side authority is essential for money, inventory, permissions, and other correctness-critical operations.", "Operational tooling should be part of the product, not only external dashboards known to the developer.", "Root-cause debugging is more valuable than applying the first obvious fix.", "Numbered invariants and explicit lifecycle rules make complex operational systems easier to review and extend.", "A maintainable admin system is a product in its own right, not a secondary collection of CRUD screens."],
    metrics: { devTime: "August 2026 – Present", commits: "334+", technologies: "Next.js 16, React 19, TypeScript, PostgreSQL, Prisma, Auth.js, Zustand, Vercel, Resend, Sentry" },
    timeline: [
      { label: "August 2026", description: "Core application structure, database, storefront, authentication, and deployment established" },
      { label: "August 2026", description: "Security, rate limiting, cross-tab synchronization, and admin hardening" },
      { label: "August 2026", description: "Inventory architecture and operational workflows implemented and aligned across ordering channels" },
      { label: "August 2026 onward", description: "Production hardening, performance optimization, CMS expansion, monitoring, and business-operation improvements" },
    ],
    recruiterSummary: {
      role: "Solo Freelance Full-Stack Developer",
      responsibilities: ["Translated client requirements into a production commerce and operations platform", "Designed the storefront, administrative system, database model, authentication, and inventory architecture", "Implemented full-stack features across commerce, inventory, CMS, returns, customer operations, security, and monitoring", "Built production deployment and CI workflows", "Designed server-authoritative business rules for money, permissions, and stock", "Maintained the application through systematic testing, auditing, debugging, and performance work"],
      impact: ["Delivered a real production e-commerce platform used by a client business", "Replaced fragmented operational workflows with a centralized administrative environment", "Built a unified inventory model supporting retail, wholesale, production, transfers, adjustments, and returns", "Reduced operational dependence on the developer by giving staff direct control of store functions", "Established a secure, observable, maintainable foundation for continued business growth"],
      technologies: ["Next.js 16", "React 19", "TypeScript", "PostgreSQL", "Prisma", "Neon", "Auth.js", "Zustand", "Vercel", "Resend", "Sentry"],
      skills: ["Full-stack product delivery", "database design", "inventory domain modeling", "authorization", "transactional systems", "debugging", "CI/CD", "production operations", "system architecture"],
    },
  },
  "ai-ecommerce": {
    title: "Bazar — AI-Integrated E-Commerce",
    oneLiner: "An AI-assisted multi-role e-commerce marketplace I built to explore how behavioral data, generative AI, and traditional commerce systems can work together in a single product.",
    status: "Functional full-stack project",
    duration: "May 2026 – July 2026",
    role: "Solo Full-Stack Developer",
    teamSize: "1",
    links: { demo: "", github: "https://github.com/Himesh-Bhattarai/ai-powered-ecommerce", docs: "" },
    overview: {
      purpose: "Build an e-commerce marketplace where product discovery becomes more relevant through AI-assisted search, behavioral recommendations, and generated product support content.",
      targetUsers: "Buyers searching and purchasing products; sellers onboarding and managing products; guest users receiving session-based recommendations.",
      businessProblem: "",
      objectives: ["Buyer and seller authentication flows", "Seller onboarding", "Product catalog", "Server-backed cart and wishlist", "Order APIs", "AI product search", "Behavioral recommendation engine", "AI review and FAQ capabilities", "Password reset and OTP flows", "Role-aware authorization"],
    },
    techStack: {
      frontend: ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS v4", "Zustand", "React Compiler"].map(nw),
      backend: ["Next.js Route Handlers", "Node.js crypto utilities", "Axios-based client communication"].map(nw),
      database: ["MongoDB", "Mongoose", "13 domain models"].map(nw),
      auth: ["Custom HMAC-SHA256 JWT implementation", "Access and refresh tokens", "scrypt password hashing", "Cookie-based authentication"].map(nw),
      ai: ["OpenAI SDK using Google's Gemini OpenAI-compatible endpoint", "Gemini 2.5 Flash Lite", "AI-assisted search, FAQ generation, review processing, and recommendations"].map(nw),
      devops: [],
      deployment: [],
      libraries: [],
    },
    features: [
      { name: "AI Product Search", description: "I implemented an AI-assisted search layer that works alongside deterministic local keyword matching.", implementation: "The architecture supports graceful fallback so product discovery does not become completely dependent on the model provider.", challenges: "", benefits: "" },
      { name: "Personalization & Recommendations", description: "Recommendations use actual behavior-related models instead of only category matching. Behavioral data includes UserEvent, UserIntent, UserPreference, RecommendationLog.", implementation: "The recommendation layer supports authenticated users and guest sessionId flows.", challenges: "", benefits: "" },
      { name: "Seller Onboarding & Dashboard", description: "A multi-step seller onboarding experience collects identity and business information before entering the seller dashboard.", implementation: "Seller and SellerInfo models separate account identity from business-specific profile data.", challenges: "", benefits: "" },
      { name: "Server-Backed Cart & Wishlist", description: "Cart and wishlist are persisted in MongoDB instead of depending only on browser storage.", implementation: "This allows logged-in users to preserve shopping state across sessions and devices.", challenges: "", benefits: "" },
      { name: "AI FAQ Generation", description: "Product-specific FAQ generation combines AI output with persistent storage through the Faqs model.", implementation: "This creates reusable support content rather than generating the same answers repeatedly.", challenges: "", benefits: "" },
      { name: "Authentication & Account Recovery", description: "Buyer login/signup, seller login/signup, access token + refresh token lifecycle, OTP-based forgotten-password flow, logged-in password reset, cookie-based session handling.", implementation: "", challenges: "", benefits: "" },
    ],
    architecture: {
      flow: ["Frontend", "Next.js API routes", "authentication / AI / personalization / database services", "MongoDB", "Gemini"],
      folderStructure: "AI concerns isolated in lib/ai, authentication in lib/auth and lib/jwt, and recommendation logic in lib/personalization.",
      appFlow: "",
      authFlow: "",
      requestLifecycle: "",
    },
    databaseDesign: {
      collections: [
        { name: "Commerce", notes: "Product, Order, Cart, Wishlist, Review" },
        { name: "Accounts", notes: "User, Seller, SellerInfo" },
        { name: "Personalization", notes: "UserEvent, UserIntent, UserPreference, RecommendationLog" },
        { name: "AI Content", notes: "Faqs" },
      ],
      reasoning: "The separation allows recommendation logic to grow independently from the core commerce entities.",
    },
    apiDocsNote: "",
    apiDocs: [
      { method: "POST", url: "/api/login", purpose: "Buyer login", auth: "" },
      { method: "POST", url: "/api/signup", purpose: "Buyer registration", auth: "" },
      { method: "POST", url: "/api/seller-login", purpose: "Seller login", auth: "" },
      { method: "POST", url: "/api/seller-signup", purpose: "Seller onboarding", auth: "" },
      { method: "GET", url: "/api/me", purpose: "Buyer session", auth: "" },
      { method: "GET", url: "/api/seller-me", purpose: "Seller session", auth: "" },
      { method: "POST", url: "/api/refreshToken", purpose: "Token rotation", auth: "" },
      { method: "POST", url: "/api/logout", purpose: "Session termination", auth: "" },
      { method: "POST", url: "/api/forgot-password/send-otp", purpose: "Send reset OTP", auth: "" },
      { method: "POST", url: "/api/forgot-password/reset-password", purpose: "Complete OTP reset", auth: "" },
      { method: "POST", url: "/api/password-reset", purpose: "Authenticated password change", auth: "" },
      { method: "GET/POST/PATCH/DELETE", url: "/api/products", purpose: "Product operations", auth: "" },
      { method: "GET/PATCH/DELETE", url: "/api/cart", purpose: "Cart operations", auth: "" },
      { method: "GET/POST/DELETE", url: "/api/watchList", purpose: "Wishlist operations", auth: "" },
      { method: "POST/GET", url: "/api/order", purpose: "Order creation and retrieval", auth: "" },
      { method: "GET", url: "/api/ai-search", purpose: "AI-assisted product search", auth: "" },
      { method: "POST", url: "/api/ai-review", purpose: "AI-assisted review processing", auth: "" },
      { method: "GET/POST", url: "/api/faq", purpose: "FAQ persistence", auth: "" },
      { method: "POST", url: "/api/ai-faq", purpose: "AI FAQ generation", auth: "" },
      { method: "POST", url: "/api/recommendations", purpose: "Personalized recommendations", auth: "" },
    ],
    authFlow: {
      login: "Credentials → scrypt verification → JWT access/refresh tokens → httpOnly cookies → per-route role validation.",
      jwt: "Custom implementation covering token signing/verification, expiry handling, refresh-token rotation, cookie lifecycle, buyer/seller role separation, and password recovery flows.",
      middleware: "",
      notes: "",
    },
    challenges: [
      { problem: "Maintaining Consistent Auth Contracts — as the number of account routes grew, keeping payload and cookie conventions aligned became important.", why: "", solution: "I standardized token payload handling and authentication helpers so buyer, seller, refresh, recovery, and logout flows use the same conventions.", tradeoffs: "", lessons: "" },
      { problem: "Moving Shopping State to the Server — the project evolved from client-only state toward persisted cart and wishlist models.", why: "", solution: "This improved cross-session behavior and made the commerce state consistent with the rest of the backend architecture.", tradeoffs: "", lessons: "" },
      { problem: "AI Fallback Design — AI features should improve the product rather than become a single point of failure.", why: "", solution: "Search therefore combines model-assisted behavior with deterministic local matching, allowing useful results even when AI configuration changes.", tradeoffs: "", lessons: "" },
    ],
    performance: { lighthouse: "", techniques: ["React Compiler enabled", "Turbopack", "Server-backed data access", "AI fallback paths", "API routes separated by responsibility", "MongoDB models aligned around specific workloads"] },
    security: { considerations: ["scrypt password hashing", "HMAC-SHA256 signed JWTs", "Access/refresh token separation", "Cookie-based sessions", "Role-aware API access", "Password recovery flows", "Server-side ownership checks for user-specific resources", "Environment-driven credentials for database and AI services"] },
    deployment: { hosting: "Structured as a production-buildable Next.js application with environment-driven MongoDB, JWT, AI, and email configuration.", cicd: "", prodSetup: "" },
    futureImprovements: ["More sophisticated recommendation ranking", "Seller analytics", "Production payment integrations", "Automated tests across commerce and auth lifecycles", "Richer admin tooling"],
    lessonsLearned: ["Behavioral models make personalization more extensible than hardcoded category rules.", "AI works best as an enhancement with deterministic fallback behavior.", "Auth contracts should be centralized early as the number of protected routes grows.", "Persisted cart and wishlist state produces a stronger multi-device commerce experience.", "Custom cryptographic/auth implementations are valuable learning exercises but require strict consistency and testing."],
    metrics: { devTime: "May 2026 – July 2026", commits: "19 (original commit history)", technologies: "Next.js, React, TypeScript, MongoDB, Mongoose, Gemini, OpenAI SDK" },
    timeline: [
      { label: "May 2026", description: "Project initialized" },
      { label: "June 2026", description: "Core marketplace, seller flows, APIs, and authentication developed" },
      { label: "June 2026", description: "Audit-driven API refinement and server-backed commerce state" },
      { label: "July 2026", description: "Session/auth lifecycle improvements and stabilization" },
    ],
    recruiterSummary: {
      role: "Solo Full-Stack Developer",
      responsibilities: ["Designed a 13-model MongoDB commerce and personalization schema", "Built buyer and seller authentication", "Implemented custom JWT and scrypt-based security", "Developed product, order, cart, wishlist, and seller flows", "Integrated Gemini through the OpenAI-compatible SDK", "Built AI-assisted search, recommendations, review processing, and FAQ generation"],
      impact: ["Produced a functional AI-assisted marketplace architecture", "Connected behavioral data directly to recommendation logic", "Implemented persistent commerce state across cart and wishlist", "Gained end-to-end experience integrating AI into conventional transactional application architecture"],
      technologies: ["Next.js", "React", "TypeScript", "MongoDB", "Mongoose", "OpenAI SDK", "Gemini"],
      skills: ["AI integration", "personalization architecture", "authentication", "MongoDB schema design", "full-stack commerce development"],
    },
  },

  contentflow: {
    title: "ContentFlow CMS",
    oneLiner: "An open-source, multi-tenant, API-first CMS I designed and built for website owners, agencies, and developers who need a self-hostable content platform with visual editing, REST APIs, integrations, backups, and production deployment tooling.",
    status: "Released — v1.0.0",
    duration: "December 2025 – February 2026",
    role: "Solo Full-Stack Developer / Open-Source Maintainer",
    teamSize: "Primarily solo, with one external contribution",
    links: { demo: "https://contentflow.duckdns.org", github: "https://github.com/Himesh-Bhattarai/Open_Source_CMS", docs: "" },
    overview: {
      purpose: "Build a modular CMS that combines no-code content management with an API-first architecture and real multi-tenancy.",
      targetUsers: "Website owners; agencies managing multiple client sites; developers consuming CMS content through APIs and webhooks.",
      businessProblem: "",
      objectives: ["Multi-tenant site management", "Block-based page building", "REST API access", "Authentication and OAuth", "API key management", "Backups", "Integrations", "CI/CD", "Open-source release discipline"],
    },
    techStack: {
      frontend: ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS 4", "Radix UI", "Sonner", "React Hook Form", "Zod", "Framer Motion", "Recharts", "Embla Carousel", "cmdk", "vaul"].map(nw),
      backend: ["Express 4", "Mongoose 8"].map(nw),
      database: ["MongoDB", "19 Mongoose models"].map(nw),
      auth: ["JWT access + refresh tokens", "express-session", "bcrypt/bcryptjs", "Google OAuth", "Facebook OAuth", "Passport"].map(nw),
      ai: [],
      devops: ["Redis", "PM2", "GitHub Actions", "Ubuntu VPS"].map(nw),
      deployment: [],
      libraries: ["Jest", "mongodb-memory-server", "Supertest", "fast-check", "Playwright", "k6"].map(nw),
    },
    features: [
      { name: "Multi-Tenant Site Builder", description: "A single deployment can manage multiple independent tenant sites: page builder, blog, forms, menus, footer management, media, SEO, themes, templates, users, integrations, backups, activity, notifications.", implementation: "Tenant-scoped data and slug constraints preserve separation between sites.", challenges: "", benefits: "This turns ContentFlow into more than an admin interface; it can act as a content platform for other frontends." },
      { name: "External Content API", description: "I built a dedicated external API for applications that consume CMS content.", implementation: "API-key authentication, Redis-backed rate limiting, domain extraction, tenant-aware content access, published-content filtering.", challenges: "", benefits: "" },
      { name: "Authentication, OAuth & CSRF Protection", description: "Email/password authentication, Google OAuth, Facebook OAuth, access/refresh tokens, session cookies, explicit CSRF protection for cookie-authenticated write operations.", implementation: "", challenges: "", benefits: "" },
      { name: "Automated Backups", description: "Backup models, routes, and scheduler services support automated backup workflows and restore operations.", implementation: "", challenges: "", benefits: "" },
      { name: "Operational Tooling", description: "/metrics Prometheus-style endpoint, TTFB smoke checks, k6 load tests, CI validation, health-check-driven deployments, automatic rollback behavior.", implementation: "", challenges: "", benefits: "" },
    ],
    architecture: {
      flow: ["Next.js client/admin", "REST API", "Express", "route/controller/service layers", "validation/security middleware", "Mongoose", "MongoDB"],
      folderStructure: "Monorepo with independent Client/ and Server/ applications plus shared quality, deployment, and documentation tooling.",
      appFlow: "Redis is used for API-key rate limiting.",
      authFlow: "",
      requestLifecycle: "",
    },
    databaseDesign: {
      collections: [
        { name: "Tenant & Publishing", notes: "Tenant, Page, Version, Blog, Menu, Footer, Form, Field, Theme, Seo, Media" },
        { name: "Platform & Integration", notes: "Client, ApiKey, Webhook, Integration" },
        { name: "Operations", notes: "ActivityLog, Notification, Feedback, Backup" },
      ],
      reasoning: "Tenant and slug relationships are designed to support multiple independent sites from one installation.",
    },
    apiDocsNote: "The application exposes versioned REST routes under /api/v1/*, with route ownership documented in the repository's API route map. Primary API surfaces cover authentication, tenant content, pages, blog, menu, footer, forms, themes, media, backups, API keys, integrations, webhooks, and external content access.",
    apiDocs: [],
    authFlow: {
      login: "Email/password or OAuth → Passport / JWT issuance → access + refresh session → role/tenant validation → protected operation.",
      jwt: "",
      middleware: "CSRF protection applies to cookie-authenticated state-changing requests.",
      notes: "",
    },
    challenges: [
      { problem: "Tenant Isolation — one platform serves multiple client websites without allowing cross-tenant content collisions.", why: "", solution: "I built tenant-scoped persistence and compound uniqueness rules such as { tenantId, slug }.", tradeoffs: "", lessons: "" },
      { problem: "Public Content Safety — public APIs must expose published content without leaking drafts.", why: "", solution: "I centralized publication filtering across external content reads before the v1.0.0 release.", tradeoffs: "", lessons: "" },
      { problem: "Production Readiness — a self-hostable CMS needs more than functional screens.", why: "", solution: "I added CI, automated deployment, health checks, rollback, load testing, performance smoke gates, operational metrics, documentation, release process, and security guidance.", tradeoffs: "", lessons: "" },
      { problem: "OAuth & Security Integration — required several iterations because the system combines JWT, sessions, third-party identity providers, and multi-tenant application behavior.", why: "", solution: "The final architecture keeps these concerns explicit rather than hiding them behind UI-only access rules.", tradeoffs: "", lessons: "" },
    ],
    performance: { lighthouse: "", techniques: ["TTFB smoke gate", "k6 load testing", "Redis-backed rate limiting", "Server-side content caching / revalidation", "Prometheus-style metrics endpoint", "Next.js server rendering"] },
    security: { considerations: ["JWT access and refresh tokens", "bcrypt password hashing", "Google/Facebook OAuth", "CSRF middleware", "Redis-backed rate limiting", "SHA-256 API-key lookup", "CORS allowlist", "Published-content enforcement", "HSTS/security headers", "Dedicated SECURITY policy", "Private vulnerability reporting process"] },
    deployment: { hosting: "Ubuntu VPS", cicd: "PM2 process manager, GitHub Actions CI/CD. Deployment flow: CI builds and validates the project → release artifact packaged → uploaded over SSH → release directory created → current symlink switches atomically → PM2 reloads → health check runs → failed health check triggers automatic rollback.", prodSetup: "" },
    futureImprovements: ["Deeper observability dashboards", "More tenant-level authorization policies", "Expanded accessibility verification", "Additional deployment/database migration automation", "Broader cross-browser regression coverage"],
    lessonsLearned: ["Open-source infrastructure projects are judged by operational maturity as much as feature count.", "Tenant isolation needs to exist in the data model, not only in UI routing.", "Release, rollback, security, and contribution processes should be designed alongside the application.", "Public APIs require explicit publication and authorization boundaries.", "Written architecture and route maps significantly reduce maintenance cost in a monorepo."],
    metrics: { devTime: "December 2025 – February 2026", commits: "246", technologies: "Next.js, Express, MongoDB, Redis, Jest, Playwright, k6 (19 Mongoose models, 17 server test files, 88 Jest cases captured in review, v1.0.0 release)" },
    timeline: [
      { label: "December 2025", description: "Project initialized" },
      { label: "February 2026", description: "Security and pre-launch hardening" },
      { label: "February 2026", description: "v1.0.0 release" },
      { label: "February 2026", description: "CI, deployment, OAuth, and production workflow refinement" },
    ],
    recruiterSummary: {
      role: "Solo Full-Stack Developer / Open-Source Maintainer",
      responsibilities: ["Built a multi-tenant CMS monorepo with Next.js and Express", "Designed a 19-model MongoDB content architecture", "Implemented JWT/session authentication with Google and Facebook OAuth", "Built an API-key-authenticated external content API", "Added Redis rate limiting", "Implemented automated backup functionality", "Built CI/CD with automatic rollback", "Added Jest, Playwright, property-based, and k6 testing", "Created open-source contribution, security, changelog, release, deployment, and QA documentation"],
      impact: ["Released a publicly accessible v1.0.0 CMS", "Demonstrated multi-tenant application architecture and API design", "Built deployment and rollback infrastructure appropriate for a self-hosted platform", "Produced an open-source project that can be operated and extended by developers other than the original author"],
      technologies: ["Next.js", "React", "TypeScript", "Express", "MongoDB", "Redis", "Passport", "GitHub Actions", "PM2"],
      skills: ["Multi-tenant architecture", "API design", "security", "OAuth", "CI/CD", "testing", "open-source engineering"],
    },
  },

  stroid: {
    title: "Stroid",
    oneLiner: "A TypeScript state-management engine I designed for React and concurrent SSR, focused on deterministic state behavior across server requests, hydration, persistence, synchronization, and runtime diagnostics.",
    status: "Published npm package",
    duration: "February 2026 – June 2026",
    role: "Library Author / Maintainer",
    teamSize: "1",
    links: { demo: "https://stroid-docs.vercel.app/docs", github: "https://github.com/Himesh-Bhattarai/stroid", docs: "https://stroid-docs.vercel.app/docs" },
    overview: {
      purpose: "Solve state correctness problems that become difficult under concurrent SSR, streaming, hydration, and multi-store applications.",
      targetUsers: "React and Next.js developers who need per-request state isolation, deterministic hydration, cross-tab synchronization, persistence, computed state, runtime diagnostics, and modular tree-shakeable APIs.",
      businessProblem: "",
      objectives: [],
    },
    techStackNote: "Current published line: v0.1.x",
    techStack: {
      frontend: ["TypeScript", "React peer integration", "AsyncLocalStorage"].map(nw),
      backend: [],
      database: [],
      auth: [],
      ai: [],
      devops: ["Vitest", "Node test runner", "tsup", "API Extractor", "publint", "Are The Types Wrong", "GitHub Actions", "release-please", "Dependabot", "CodeQL", "OSSF Scorecard"].map(nw),
      deployment: [],
      libraries: [],
    },
    features: [
      { name: "Per-Request SSR Isolation", description: "Stroid creates request-scoped state registries so concurrent requests do not share mutable application state.", implementation: "AsyncLocalStorage-backed request scopes with explicit request registry helpers.", challenges: "", benefits: "Prevents cross-request state contamination in SSR applications." },
      { name: "Post-Hydration Consistency Contracts", description: "hydrateStores(...) supports an explicit consistency contract covering snapshot metadata, store authority (server_wins, client_wins, merge, invalidate_and_refetch), drift diagnostics, configurable boot windows, and deterministic early-write replay.", implementation: "", challenges: "", benefits: "Hydration becomes a defined state transition rather than an implicit race between server state and early client writes." },
      { name: "Modular Subpath Exports", description: "Stroid exposes dedicated subpaths for core, React, server, persistence, synchronization, selectors, runtime tools, async state, testing, and other capabilities.", implementation: "", challenges: "", benefits: "Consumers import only the functionality they need, improving tree-shaking and making the package surface explicit." },
      { name: "Runtime Introspection", description: "Runtime tooling exposes store discovery, metrics, store health, hydration consistency state, drift events, drift metrics, and DevTools history/redaction.", implementation: "", challenges: "", benefits: "" },
      { name: "Persistence & Synchronization", description: "Persistence supports browser storage, checksums, and migrations. Synchronization supports BroadcastChannel, cross-tab state propagation, and worker-style synchronization.", implementation: "Features self-register through hooks so unused modules do not impose the same runtime cost as always-on functionality.", challenges: "", benefits: "" },
    ],
    architecture: {
      flow: ["Public API", "Core runtime", "Store lifecycle", "Notification pipeline", "Feature modules", "Computed graph", "Async utilities", "React/server/runtime integrations", "Internal diagnostics"],
      folderStructure: "",
      appFlow: "The store name acts as the stable address used across read, write, subscribe, persist, sync, compute, and debugging operations.",
      authFlow: "",
      requestLifecycle: "",
    },
    databaseDesign: { collections: [], reasoning: "Not applicable — client-side state library, no database." },
    apiDocsNote: "Stroid is a package API rather than a REST API. Documentation includes generated API references and topic-based guides for Core, Architecture, Server, React, Persistence, Sync, Testing, Migration, TypeScript, Configuration, DevTools, and FAQ.",
    apiDocs: [],
    authFlow: { notes: "Not applicable — client-side state library, no auth surface." },
    challenges: [
      { problem: "Tree-Shakeable Feature Growth — supporting many optional capabilities without forcing every consumer to bundle them.", why: "", solution: "I designed a multi-entry package with explicit subpath exports, normalized type declarations, and publish-surface validation.", tradeoffs: "", lessons: "" },
      { problem: "Hydration Determinism — storage events, effects, network responses, and sync messages can all write during hydration.", why: "", solution: "I introduced authority policies, boot-window write deferral, deterministic replay, and drift observability.", tradeoffs: "", lessons: "" },
      { problem: "Concurrency Certification — correctness under race conditions is difficult to demonstrate with normal unit tests alone.", why: "", solution: "I built a large first-party benchmark and adversarial test suite covering SSR isolation, hydration divergence, randomized timing, large payloads, WebSocket/sync streams, atomic failure, race conditions, memory behavior, and production-like scenarios.", tradeoffs: "", lessons: "" },
    ],
    performance: { lighthouse: "Not applicable — not a web page.", techniques: ["Tree-shakeable subpath exports", "Lazy feature lifecycle short-circuiting", "Computed graph ordering memoization", "Request isolation without a global lock", "Dedicated core-operation benchmarks", "Large-payload hydration benchmarks", "React concurrency benchmarks"] },
    security: { considerations: ["GitHub Security Advisories", "CodeQL", "OSSF Scorecard", "Dependency review", "Dependabot", "Explicit GitHub Actions token permissions", "Pinned workflow actions where appropriate", "Controlled npm publishing", "Automated release process"] },
    deployment: { hosting: "Published to npm with automated release and publishing workflows.", cicd: "Release pipeline separates version/changelog generation, test and quality gates, GitHub release creation, and npm publication.", prodSetup: "" },
    futureImprovements: ["SSR/runtime interoperability", "Developer ergonomics", "Hydration diagnostics", "Performance certification", "Documentation", "Framework compatibility"],
    lessonsLearned: ["Library architecture includes packaging, types, exports, documentation, and release tooling—not only runtime logic.", "Concurrent SSR problems are often ordering problems rather than simple state-update problems.", "Deterministic reconciliation rules are more useful than assuming one universal hydration policy.", "A package's published surface should be tested as carefully as its internal implementation.", "Security and supply-chain controls matter even when the project does not run its own server."],
    metrics: { devTime: "February 2026 – June 2026", commits: "488 (captured in review)", technologies: "TypeScript, React, AsyncLocalStorage, Vitest, tsup, GitHub Actions (multiple tagged releases, ~20 explicit entry points, 30+ benchmark scripts)" },
    timeline: [
      { label: "February 2026", description: "Project started" },
      { label: "March 2026", description: "Initial public releases" },
      { label: "April 2026", description: "Post-hydration consistency and server-portability work" },
      { label: "April–June 2026", description: "Hardening, benchmarks, regression coverage, packaging, and dependency maintenance" },
    ],
    recruiterSummary: {
      role: "Solo Library Author / Maintainer",
      responsibilities: ["Designed a TypeScript state engine for concurrent SSR", "Implemented per-request isolation", "Designed post-hydration reconciliation contracts", "Built React integration around useSyncExternalStore", "Created modular subpath exports", "Built persistence, synchronization, computed state, async state, runtime diagnostics, and developer tooling", "Built automated releases, npm publication, security scanning, and package-surface validation", "Created extensive adversarial benchmark and regression coverage"],
      impact: ["Published a real npm package with versioned releases", "Built a state architecture focused on correctness under concurrent rendering", "Demonstrated package design, API stability, release engineering, testing, and supply-chain security beyond normal application development"],
      technologies: ["TypeScript", "React", "AsyncLocalStorage", "Vitest", "tsup", "GitHub Actions"],
      skills: ["Library architecture", "TypeScript API design", "SSR", "hydration", "concurrency", "testing", "release engineering"],
    },
  },

  "portfolio-v2": {
    title: "Portfolio v2",
    oneLiner: "My personal portfolio is built as a real full-stack application rather than a static collection of pages. It combines a MongoDB-backed content system, admin authentication, project case studies, Vercel Blob media, and an AI-assisted administrative workflow.",
    status: "Active production portfolio",
    duration: "March 2025 – Present",
    role: "Solo Full-Stack Developer",
    teamSize: "1",
    links: { demo: "", github: "https://github.com/Himesh-Bhattarai/_Portfolio", docs: "" },
    overview: {
      purpose: "Use my own portfolio as a practical demonstration of architecture, backend development, data modeling, authentication, cloud infrastructure, and AI-assisted administration.",
      targetUsers: "Recruiters; engineering managers; developers reviewing my work; myself as the content administrator.",
      businessProblem: "",
      objectives: ["Database-backed homepage", "Database-backed project detail pages", "Blog CMS", "Admin authentication", "Vercel Blob screenshot management", "AI-assisted content administration", "MongoDB-based content source of truth"],
    },
    techStack: {
      frontend: ["Next.js 16", "React 19", "Tailwind CSS", "Radix UI", "Framer Motion", "Three.js / React Three Fiber"].map(nw),
      backend: ["Next.js Server Components", "API Route Handlers", "Server-side auth utilities"].map(nw),
      database: ["MongoDB Atlas", "Mongoose"].map(nw),
      auth: ["JWT", "bcryptjs", "httpOnly cookies"].map(nw),
      ai: ["MCP server", "MongoDB MCP integration", "AI-assisted admin tooling"].map(nw),
      devops: [],
      deployment: ["Vercel", "Vercel Blob", "MongoDB Atlas", "Resend"].map(nw),
      libraries: [],
    },
    features: [
      { name: "Database-Backed Homepage", description: "Homepage sections render from a single MongoDB Content document: Navbar, Hero, About, Experience, Resume, Work, Contact, Footer.", implementation: "", challenges: "", benefits: "This keeps display components focused on rendering while the database owns editable content." },
      { name: "Blog CMS", description: "The blog supports public reads, authenticated admin creation, editing, and deletion.", implementation: "Blog content is persisted through Mongoose rather than hardcoded in components.", challenges: "", benefits: "" },
      { name: "Database-Backed Project Case Studies", description: "Each project detail page is stored as a Project document, with structured sections: overview, tech stack, features, architecture, database design, API documentation, authentication, challenges, performance, security, deployment, improvements, lessons, metrics, timeline, recruiter summary, screenshots.", implementation: "Vercel Blob stores project media rather than coupling screenshots to local source paths.", challenges: "", benefits: "" },
      { name: "AI-Assisted Administration", description: "The portfolio includes an MCP-backed administration layer designed to let me manage content conversationally.", implementation: "", challenges: "", benefits: "The security boundary remains server-authoritative: AI output can request an action, but authorization is determined independently by the application." },
      { name: "Cloud Infrastructure Automation", description: "I configured MongoDB Atlas, Vercel environment variables, Blob storage, and MCP tooling through CLI-based workflows where possible.", implementation: "", challenges: "", benefits: "" },
    ],
    architecture: {
      flow: ["Next.js Server Components", "server-side data layer", "MongoDB Atlas", "structured Content/Project/Blog models", "Vercel Blob for media"],
      folderStructure: "",
      appFlow: "Administrative requests pass through authenticated server-side boundaries before content mutations are allowed.",
      authFlow: "",
      requestLifecycle: "",
    },
    databaseDesign: {
      collections: [
        { name: "Content", notes: "Single document for site-wide homepage content" },
        { name: "Project", notes: "One document per project slug, allowing each case study to evolve independently" },
        { name: "Blog", notes: "One document per post with title, description, image, body, and timestamps" },
      ],
      reasoning: "This model keeps the content architecture simple while avoiding duplicated hardcoded data across components.",
    },
    apiDocsNote: "",
    apiDocs: [
      { method: "POST", url: "/api/contact", purpose: "Send contact email", auth: "" },
      { method: "POST", url: "/api/admin-login", purpose: "Authenticate administrator", auth: "" },
      { method: "GET/POST/PATCH/DELETE", url: "/api/blog", purpose: "Blog content operations", auth: "" },
      { method: "POST", url: "/api/chat", purpose: "AI/MCP orchestration", auth: "" },
      { method: "GET/PATCH", url: "Project/content APIs", purpose: "CMS-backed portfolio content operations", auth: "" },
    ],
    authFlow: { login: "Admin credentials → bcrypt verification → JWT issuance → httpOnly cookie → server validation → authorized mutation.", jwt: "", middleware: "", notes: "AI-admin capabilities use the same server authorization boundary and do not trust model output as proof of identity." },
    challenges: [
      { problem: "Removing Multiple Sources of Truth — content had accumulated across legacy and component-level structures during framework evolution.", why: "", solution: "I consolidated homepage content into one MongoDB-backed source and made rendering components receive data rather than own duplicated content.", tradeoffs: "", lessons: "" },
      { problem: "Vite-to-Next.js Migration — the original application architecture used Vite-specific patterns.", why: "", solution: "I migrated the application to Next.js App Router and progressively moved data loading to Server Components.", tradeoffs: "", lessons: "" },
      { problem: "Building Safe AI Administration — an AI agent with write capability needs stronger security boundaries than a normal chatbot.", why: "", solution: "I separated model intent from application authorization. The server decides which tools/actions are available based on the authenticated session.", tradeoffs: "", lessons: "" },
      { problem: "Structured PDP Content — large project case studies become difficult to maintain when stored as massive inline objects.", why: "", solution: "I moved project content into MongoDB Project documents and media into Vercel Blob.", tradeoffs: "", lessons: "" },
    ],
    performance: { lighthouse: "", techniques: ["Server Components for data-driven pages", "Reduced duplicated client-side data", "Structured DB reads", "Blob-backed media", "Next.js rendering and caching capabilities", "Interactive client components isolated from server-rendered content"] },
    security: { considerations: ["bcrypt-hashed admin password", "JWT auth", "httpOnly cookies", "Gitignored environment secrets", "MongoDB/Vercel credentials stored outside source", "Server-side authorization for AI administrative actions", "Clear separation between public read capabilities and privileged mutations"] },
    deployment: { hosting: "Vercel", cicd: "", prodSetup: "Database: MongoDB Atlas · Media: Vercel Blob · Email: Resend. The deployment architecture is environment-driven and designed around the same production services used by the application locally and in hosted environments." },
    futureImprovements: ["More AI-assisted content workflows", "Richer case-study media", "Better project search and discovery", "Additional admin automation", "Expanded analytics and recruiter-focused presentation"],
    lessonsLearned: ["A portfolio is more persuasive when the architecture itself demonstrates engineering capability.", "Content should have one clear source of truth.", "AI administration requires explicit tool permissions and server-side authorization.", "Data migrations are easier when display components do not own business content.", "Cloud tooling and content infrastructure are useful portfolio evidence when they solve real maintenance problems."],
    metrics: { devTime: "March 2025 – Present", commits: "50+ (originally captured)", technologies: "Next.js, React, MongoDB Atlas, JWT, Vercel Blob, MCP" },
    timeline: [
      { label: "March 2025", description: "Initial portfolio" },
      { label: "July 2026", description: "Migration from Vite to Next.js" },
      { label: "August 2026", description: "Admin auth, MongoDB content architecture, project PDP system, Blob media, and MCP-assisted administration" },
      { label: "Ongoing", description: "Content refinement, infrastructure hardening, and recruiter-facing improvements" },
    ],
    recruiterSummary: {
      role: "Solo Full-Stack Developer",
      responsibilities: ["Migrated a real application from Vite to Next.js", "Built JWT-based admin authentication", "Built MongoDB-backed homepage, blog, and project-content systems", "Designed Vercel Blob media storage", "Created MCP/AI-assisted admin workflows", "Consolidated duplicated content into a database source of truth", "Structured project case studies as editable data rather than hardcoded JSX"],
      impact: ["Turned a static portfolio into a maintainable full-stack product", "Reduced content duplication", "Demonstrated backend, database, auth, cloud, and AI-integration capability through the portfolio itself"],
      technologies: ["Next.js", "React", "MongoDB Atlas", "JWT", "Vercel Blob", "MCP"],
      skills: ["Migration", "CMS design", "authentication", "cloud infrastructure", "AI tooling", "full-stack architecture"],
    },
  },

  "helmet-head": {
    title: "Helmet Head Nepal",
    oneLiner: "A modern motorcycle helmet and riding-accessories e-commerce project focused on product presentation, immersive visuals, and a clean shopping experience.",
    status: "Functional project",
    duration: "",
    role: "Full-Stack Developer",
    teamSize: "",
    links: { demo: "", github: "https://github.com/Himesh-Bhattarai/HELMETHEADS-NEPAL", docs: "" },
    overview: {
      purpose: "Build a specialized online storefront for motorcycle helmets and riding accessories with a stronger visual identity than a generic marketplace.",
      targetUsers: "Motorcycle riders; helmet buyers; customers browsing riding accessories.",
      businessProblem: "",
      objectives: ["Product-focused e-commerce experience", "Strong visual presentation", "Responsive storefront", "Structured product browsing", "Modern interactive UI"],
    },
    techStack: {
      frontend: ["Next.js", "React", "Tailwind CSS", "Three.js"].map(nw),
      backend: ["Express"].map(nw),
      database: [],
      auth: [],
      ai: [],
      devops: [],
      deployment: [],
      libraries: ["JavaScript / TypeScript web tooling"].map(nw),
    },
    features: [
      { name: "Product Catalog", description: "Structured browsing for helmets and accessories with product-focused presentation.", implementation: "", challenges: "", benefits: "" },
      { name: "Product Detail Experience", description: "Detailed product views designed to highlight helmet styling, specifications, imagery, and purchasing information.", implementation: "", challenges: "", benefits: "" },
      { name: "Interactive Visual Layer", description: "Three.js supports richer visual presentation and gives the project a differentiated product-showcase experience.", implementation: "", challenges: "", benefits: "" },
      { name: "Responsive Commerce UI", description: "The storefront is designed for desktop and mobile browsing with modern navigation and purchase-oriented page structure.", implementation: "", challenges: "", benefits: "" },
    ],
    architecture: {
      flow: ["Frontend commerce experience", "product/application services", "Express backend", "data persistence layer"],
      folderStructure: "",
      appFlow: "The project separates visual presentation from backend commerce responsibilities so each layer can evolve independently.",
      authFlow: "",
      requestLifecycle: "",
    },
    databaseDesign: { collections: [{ name: "Commerce model", notes: "Products, product categories, product media, customer/account data, cart/order information" }], reasoning: "" },
    apiDocsNote: "Server interfaces support the core e-commerce lifecycle: product retrieval, product detail, cart operations, order operations, account/authentication operations.",
    apiDocs: [],
    authFlow: { notes: "Customer authentication follows the standard web-commerce pattern of server-validated credentials and protected account/order operations." },
    challenges: [],
    performance: { lighthouse: "", techniques: ["Componentized rendering", "Responsive media", "Interactive visuals scoped to relevant surfaces", "Separation between standard commerce UI and heavier 3D experiences"] },
    security: { considerations: ["Server-side validation for privileged operations", "Protected account/order operations", "Environment-based configuration for backend credentials"] },
    deployment: { hosting: "Structured for standard web deployment with independently maintainable frontend and backend responsibilities.", cicd: "", prodSetup: "" },
    futureImprovements: ["Richer 3D product interaction", "Fit/size guidance", "Comparison tools", "Brand and certification filtering", "Inventory-aware merchandising"],
    lessonsLearned: ["3D should support product understanding rather than distract from conversion.", "Specialized commerce sites benefit from domain-specific filters and content.", "Visual ambition still needs a straightforward purchasing path.", "Engineering focus: combining immersive product presentation with a usable e-commerce flow without allowing visual effects to interfere with product discovery or purchase intent."],
    metrics: { devTime: "", commits: "", technologies: "Next.js, React, Tailwind CSS, Three.js, Express" },
    timeline: [],
    recruiterSummary: {
      role: "Full-Stack Developer",
      responsibilities: ["Designed a specialized helmet-commerce experience", "Combined Next.js/Tailwind UI development with Three.js visual work", "Structured frontend and backend responsibilities for commerce functionality"],
      impact: ["Demonstrates my ability to combine product-oriented UI, interactive visual technology, and full-stack commerce architecture."],
      technologies: ["Next.js", "React", "Tailwind CSS", "Three.js", "Express"],
      skills: [],
    },
  },

  nprevolution: {
    title: "NP Revolution",
    oneLiner: "A full-stack Nepali digital news platform combining a public news experience with reporter workflows, authentication, role-based content management, media uploads, weather information, and editorial dashboards.",
    status: "Functional full-stack project",
    duration: "March–April 2025",
    role: "Solo Full-Stack Developer",
    teamSize: "1",
    links: { demo: "", github: "https://github.com/Himesh-Bhattarai/NP_NEWS_PORTAL", docs: "" },
    overview: {
      purpose: "Build a modern Nepali news platform serving both readers and reporters from one application.",
      targetUsers: "News readers; reporters; editorial/admin users.",
      businessProblem: "",
      objectives: ["Categorized news homepage", "Breaking news", "Video news", "Trending content", "Weather", "Reporter dashboard", "Content creation", "Role-based content management", "Media uploads", "Authentication", "Google OAuth", "Light/dark themes"],
    },
    techStack: {
      frontend: ["Vite", "React 19", "React Router", "Tailwind CSS", "Radix UI / shadcn-style components", "Lucide React", "React Icons"].map(nw),
      backend: ["Express 4", "Joi", "Multer", "Helmet"].map(nw),
      database: ["MongoDB", "Mongoose"].map(nw),
      auth: ["JWT", "bcryptjs", "Passport", "Google OAuth", "Cookie sessions"].map(nw),
      ai: [],
      devops: [],
      deployment: [],
      libraries: [],
    },
    features: [
      { name: "News Homepage", description: "Breaking-news ticker, hero stories, editor's picks, live updates, trusted sources, popular tags, trending topics, category-grouped news, video stories, newsletter signup, weather.", implementation: "The UI is decomposed into reusable content and editorial components.", challenges: "", benefits: "" },
      { name: "Reporter Dashboard", description: "Article statistics, view and engagement information, draft/published/review states, content shortcuts, editorial calendar, trending story opportunities, fact-checking tools.", implementation: "", challenges: "", benefits: "" },
      { name: "Content CRUD", description: "Structured content management with public article reads, reporter-authorized writes, draft/published/archived states, view tracking, tags and categories, media attachments, ownership validation.", implementation: "", challenges: "", benefits: "" },
      { name: "Media Uploads", description: "Multer handles media upload workflows with validation for supported image/video formats and controlled file limits.", implementation: "", challenges: "", benefits: "" },
      { name: "Authentication", description: "Email/password registration and login, JWT authentication, reporter role validation, Google OAuth, token verification.", implementation: "", challenges: "", benefits: "" },
      { name: "Weather Integration", description: "The homepage integrates current weather data to enrich the local news experience.", implementation: "", challenges: "", benefits: "" },
      { name: "Theme System", description: "A persistent light/dark theme preference is stored in the browser and applied at the document level.", implementation: "", challenges: "", benefits: "" },
    ],
    architecture: {
      flow: ["React/Vite frontend", "Axios/API layer", "Express", "authentication/validation/upload middleware", "controllers", "Mongoose", "MongoDB"],
      folderStructure: "Backend separates controllers, middleware, models, routes, upload utilities, and authentication configuration.",
      appFlow: "",
      authFlow: "",
      requestLifecycle: "",
    },
    databaseDesign: {
      collections: [
        { name: "User", notes: "Username, email, password hash, role, timestamps" },
        { name: "Reporter", notes: "User reference, verification status, biography" },
        { name: "Content", notes: "Title, body, author, media, category, tags, publication status, views, created/updated timestamps" },
      ],
      reasoning: "The model supports a clear reader/reporter/editor workflow.",
    },
    apiDocsNote: "",
    apiDocs: [
      { method: "POST", url: "/api/auth/register", purpose: "Register account", auth: "Public" },
      { method: "POST", url: "/api/auth/login", purpose: "Login", auth: "Public" },
      { method: "GET", url: "/api/auth/verify-token", purpose: "Verify token", auth: "Authenticated" },
      { method: "GET", url: "/api/auth/google", purpose: "Google OAuth", auth: "Public" },
      { method: "GET", url: "/api/auth/google/callback", purpose: "OAuth callback", auth: "Google auth" },
      { method: "GET", url: "/api/content", purpose: "List content", auth: "Public" },
      { method: "GET", url: "/api/content/:id", purpose: "Read article", auth: "Public" },
      { method: "POST", url: "/api/content", purpose: "Create content", auth: "Reporter" },
      { method: "PUT", url: "/api/content/:id", purpose: "Update content", auth: "Reporter/owner" },
      { method: "DELETE", url: "/api/content/:id", purpose: "Delete content", auth: "Reporter/owner" },
    ],
    authFlow: { login: "Email/password → bcrypt verification → JWT issuance → authenticated API request → user resolution → reporter-role validation where required.", jwt: "", middleware: "", notes: "Google OAuth provides an additional third-party sign-in path through Passport." },
    challenges: [
      { problem: "Aligning Frontend and Backend Contracts — a content-heavy application has many data consumers and can drift if UI and API shapes evolve separately.", why: "", solution: "I aligned authentication and content responses behind consistent client/API boundaries and connected editorial views to the backend content lifecycle.", tradeoffs: "", lessons: "" },
      { problem: "Combining JWT and OAuth — supporting both first-party credentials and Google OAuth requires a consistent application identity after authentication.", why: "", solution: "I normalized both flows into the same user/role model so downstream authorization follows one policy.", tradeoffs: "", lessons: "" },
      { problem: "Reporter Authorization — content creation must be protected by more than login status.", why: "", solution: "I composed JWT authentication with reporter-role middleware and ownership checks for protected mutations.", tradeoffs: "", lessons: "" },
    ],
    performance: { lighthouse: "", techniques: ["Vite development/build pipeline", "Componentized homepage", "Tailwind-based styling", "Client-side routing", "Reusable content components", "Efficient API separation between public reads and protected writes"] },
    security: { considerations: ["Helmet middleware", "bcrypt password hashing", "JWT authentication", "Role-based authorization", "Joi validation", "Upload restrictions", "Environment-based secrets", "CORS configuration", "Rate-limiting capability", "OAuth configuration separated from application logic"] },
    deployment: { hosting: "Separate frontend and backend packages, allowing independent deployment and scaling while sharing one MongoDB-backed content model.", cicd: "", prodSetup: "" },
    futureImprovements: ["Editorial review workflows", "Richer analytics", "Search", "Personalized feeds", "Real-time breaking-news updates", "Additional fact-checking automation", "Media processing"],
    lessonsLearned: ["Content systems need stable API contracts because many screens depend on the same entities.", "Role-based authorization must be enforced in backend middleware, not only in dashboard routing.", "File upload, authentication, validation, and business logic are easier to reason about when composed as explicit middleware stages.", "Building both reader and reporter experiences in the same product forces clearer separation between public and privileged capabilities."],
    metrics: { devTime: "March–April 2025", commits: "", technologies: "Vite, React, React Router, Tailwind, Express, MongoDB, Mongoose, Passport, JWT, Joi, Multer" },
    timeline: [
      { label: "March 2025", description: "Project initialized with frontend and backend structure" },
      { label: "April 2025", description: "Routing, dashboard, authentication, content workflow, and UI refinement" },
    ],
    recruiterSummary: {
      role: "Solo Full-Stack Developer",
      responsibilities: ["Built a componentized React news portal", "Built a reporter-focused CMS dashboard", "Implemented Express/MongoDB content APIs", "Added JWT authentication and role-based authorization", "Implemented media uploads and Joi validation", "Added Google OAuth", "Integrated weather and theme functionality", "Connected public content and reporter workflows through one backend model"],
      impact: ["Demonstrates rapid full-stack delivery across a public content product and a privileged editorial application", "Shows experience with authentication, RBAC, media upload, API design, and component-heavy React UI"],
      technologies: ["React", "Vite", "Tailwind CSS", "Express", "MongoDB", "Mongoose", "Passport", "JWT", "Joi", "Multer"],
      skills: ["Full-stack development", "content systems", "RBAC", "API design", "authentication", "media handling", "React UI architecture"],
    },
  },
};

async function main() {
  await mongoose.connect(MONGODB_URI);
  console.log("Connected to MongoDB.");
  for (const [slug, data] of Object.entries(updates)) {
    const res = await Project.updateOne({ slug }, { $set: data });
    console.log(`Updated ${slug}: matched=${res.matchedCount} modified=${res.modifiedCount}`);
  }
  await mongoose.disconnect();
  console.log("Done (batch 1 of N).");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
